clone_depth: 1

image: Visual Studio 2017
platform: x64

branches:
  only:
    - master

build_script:
  - ps: ./mesos-format.ps1

artifacts:
  - path: '*.zip'

deploy:
  - provider: BinTray
    username: mpark
    api_key:
      secure: 1kkWLQUMiwZGXqGRwLudwVr1qGIYYRHC0+aBFt7us3nUR4OfFF22L3ITt6hgMUC4
    subject: apache
    repo: mesos
    package: llvm
    version: 2018-03-08
